// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | FeatureHighlightSplitSlice
  | FeatureHighlightSplit2Slice
  | MegaFooterNavigationSlice
  | HeadlineCtaEmailSlice
  | FeatureWithVisualAndTextSlice
  | HeadlineWithDescriptionSlice
  | HeadlineWithCtaInputSlice
  | NavigationBarSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Item in *Carousel → Default → Primary → Slides*
 */
export interface FeatureHighlightSplitSliceDefaultWithThreeFeaturesPrimarySlidesItem {
  /**
   * Slide Icon field in *Carousel → Default → Primary → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split.default_with_three_features.primary.slides[].slide_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slide_icon: prismic.ImageField<never>;

  /**
   * Slide Title field in *Carousel → Default → Primary → Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split.default_with_three_features.primary.slides[].slide_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slide_title: prismic.KeyTextField;

  /**
   * Slide Description field in *Carousel → Default → Primary → Slides*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split.default_with_three_features.primary.slides[].slide_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slide_description: prismic.RichTextField;

  /**
   * Slide Image field in *Carousel → Default → Primary → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split.default_with_three_features.primary.slides[].slide_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slide_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface FeatureHighlightSplitSliceDefaultWithThreeFeaturesPrimary {
  /**
   * Label field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split.default_with_three_features.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split.default_with_three_features.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slides field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split.default_with_three_features.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slides: prismic.GroupField<
    Simplify<FeatureHighlightSplitSliceDefaultWithThreeFeaturesPrimarySlidesItem>
  >;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default_with_three_features`
 * - **Description**: Displays a section title, an optional label, a main image or visual, and a list of up to three features, each with a title and description.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureHighlightSplitSliceDefaultWithThreeFeatures =
  prismic.SharedSliceVariation<
    "default_with_three_features",
    Simplify<FeatureHighlightSplitSliceDefaultWithThreeFeaturesPrimary>,
    never
  >;

/**
 * Slice variation for *Carousel*
 */
type FeatureHighlightSplitSliceVariation =
  FeatureHighlightSplitSliceDefaultWithThreeFeatures;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `feature_highlight_split`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureHighlightSplitSlice = prismic.SharedSlice<
  "feature_highlight_split",
  FeatureHighlightSplitSliceVariation
>;

/**
 * Item in *FeatureHighlightSplit2 → Default → Primary → Features*
 */
export interface FeatureHighlightSplit2SliceDefaultPrimaryFeaturesItem {
  /**
   * Illustration field in *FeatureHighlightSplit2 → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split_2.default.primary.features[].illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Title field in *FeatureHighlightSplit2 → Default → Primary → Features*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split_2.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *FeatureHighlightSplit2 → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split_2.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *FeatureHighlightSplit2 → Default → Primary*
 */
export interface FeatureHighlightSplit2SliceDefaultPrimary {
  /**
   * Features field in *FeatureHighlightSplit2 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_highlight_split_2.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeatureHighlightSplit2SliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for FeatureHighlightSplit2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard split with two feature panels, each containing an image, heading, and description.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureHighlightSplit2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureHighlightSplit2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureHighlightSplit2*
 */
type FeatureHighlightSplit2SliceVariation = FeatureHighlightSplit2SliceDefault;

/**
 * FeatureHighlightSplit2 Shared Slice
 *
 * - **API ID**: `feature_highlight_split_2`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureHighlightSplit2Slice = prismic.SharedSlice<
  "feature_highlight_split_2",
  FeatureHighlightSplit2SliceVariation
>;

/**
 * Primary content in *FeatureWithVisualAndText → Visual Left, Text Right → Primary*
 */
export interface FeatureWithVisualAndTextSliceVisualLeftTextRightPrimary {
  /**
   * Visual Image field in *FeatureWithVisualAndText → Visual Left, Text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_with_visual_and_text.visual_left_text_right.primary.visual_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  visual_image: prismic.ImageField<never>;

  /**
   * Headline field in *FeatureWithVisualAndText → Visual Left, Text Right → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_with_visual_and_text.visual_left_text_right.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Description field in *FeatureWithVisualAndText → Visual Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_with_visual_and_text.visual_left_text_right.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Visual Left, Text Right variation for FeatureWithVisualAndText Slice
 *
 * - **API ID**: `visual_left_text_right`
 * - **Description**: Displays a visual or illustration alongside a headline and descriptive text, typically used to explain a specific feature or capability.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureWithVisualAndTextSliceVisualLeftTextRight =
  prismic.SharedSliceVariation<
    "visual_left_text_right",
    Simplify<FeatureWithVisualAndTextSliceVisualLeftTextRightPrimary>,
    never
  >;

/**
 * Slice variation for *FeatureWithVisualAndText*
 */
type FeatureWithVisualAndTextSliceVariation =
  FeatureWithVisualAndTextSliceVisualLeftTextRight;

/**
 * FeatureWithVisualAndText Shared Slice
 *
 * - **API ID**: `feature_with_visual_and_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureWithVisualAndTextSlice = prismic.SharedSlice<
  "feature_with_visual_and_text",
  FeatureWithVisualAndTextSliceVariation
>;

/**
 * Item in *FooterNavigation → Default Layout → Primary → Navigation Columns*
 */
export interface FooterNavigationSliceDefaultLayoutPrimaryNavigationColumnsItem {
  /**
   * Column Heading field in *FooterNavigation → Default Layout → Primary → Navigation Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.navigation_columns[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Navigation Item Label field in *FooterNavigation → Default Layout → Primary → Navigation Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.navigation_columns[].item_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_label: prismic.KeyTextField;

  /**
   * Navigation Link field in *FooterNavigation → Default Layout → Primary → Navigation Columns*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.navigation_columns[].item_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *FooterNavigation → Default Layout → Primary → Certification Badges*
 */
export interface FooterNavigationSliceDefaultLayoutPrimaryCertificationBadgesItem {
  /**
   * Badge Image field in *FooterNavigation → Default Layout → Primary → Certification Badges*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.certification_badges[].badge
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  badge: prismic.ImageField<never>;
}

/**
 * Item in *FooterNavigation → Default Layout → Primary → Legal Links*
 */
export interface FooterNavigationSliceDefaultLayoutPrimaryLegalLinksItem {
  /**
   * Legal Link Label field in *FooterNavigation → Default Layout → Primary → Legal Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.legal_links[].legal_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  legal_label: prismic.KeyTextField;

  /**
   * Legal Link field in *FooterNavigation → Default Layout → Primary → Legal Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.legal_links[].legal_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  legal_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *FooterNavigation → Default Layout → Primary → Social Links*
 */
export interface FooterNavigationSliceDefaultLayoutPrimarySocialLinksItem {
  /**
   * Platform field in *FooterNavigation → Default Layout → Primary → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.social_links[].platform_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform_label: prismic.KeyTextField;

  /**
   * Social Link field in *FooterNavigation → Default Layout → Primary → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.social_links[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *FooterNavigation → Default Layout → Primary*
 */
export interface FooterNavigationSliceDefaultLayoutPrimary {
  /**
   * Logo field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Columns field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.navigation_columns[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_columns: prismic.GroupField<
    Simplify<FooterNavigationSliceDefaultLayoutPrimaryNavigationColumnsItem>
  >;

  /**
   * Newsletter Description field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.newsletter_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletter_description: prismic.RichTextField;

  /**
   * Newsletter Input Placeholder field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.newsletter_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_placeholder: prismic.KeyTextField;

  /**
   * Newsletter Call to Action field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.newsletter_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  newsletter_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Certification Badges field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.certification_badges[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  certification_badges: prismic.GroupField<
    Simplify<FooterNavigationSliceDefaultLayoutPrimaryCertificationBadgesItem>
  >;

  /**
   * Company Info field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.company_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_info: prismic.RichTextField;

  /**
   * Copyright field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.copyright
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * Legal Links field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.legal_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legal_links: prismic.GroupField<
    Simplify<FooterNavigationSliceDefaultLayoutPrimaryLegalLinksItem>
  >;

  /**
   * Social Links field in *FooterNavigation → Default Layout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.default_layout.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<FooterNavigationSliceDefaultLayoutPrimarySocialLinksItem>
  >;
}

/**
 * Default Layout variation for FooterNavigation Slice
 *
 * - **API ID**: `default_layout`
 * - **Description**: Standard footer with multi-column navigation, subscription, logo, certification icons, social links, legal info.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterNavigationSliceDefaultLayout = prismic.SharedSliceVariation<
  "default_layout",
  Simplify<FooterNavigationSliceDefaultLayoutPrimary>,
  never
>;

/**
 * Slice variation for *FooterNavigation*
 */
type FooterNavigationSliceVariation = FooterNavigationSliceDefaultLayout;

/**
 * FooterNavigation Shared Slice
 *
 * - **API ID**: `footer_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterNavigationSlice = prismic.SharedSlice<
  "footer_navigation",
  FooterNavigationSliceVariation
>;

/**
 * Item in *HeaderNavigation → Default → Primary → Navigation Links*
 */
export interface HeaderNavigationSliceDefaultPrimaryNavLinksItem {
  /**
   * Link Label field in *HeaderNavigation → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.nav_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *HeaderNavigation → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.nav_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Has Dropdown field in *HeaderNavigation → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.nav_links[].has_dropdown
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_dropdown: prismic.BooleanField;
}

/**
 * Item in *HeaderNavigation → Default → Primary → Action Buttons*
 */
export interface HeaderNavigationSliceDefaultPrimaryActionButtonsItem {
  /**
   * Button Label field in *HeaderNavigation → Default → Primary → Action Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.action_buttons[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Button Link field in *HeaderNavigation → Default → Primary → Action Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.action_buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Button Style field in *HeaderNavigation → Default → Primary → Action Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.action_buttons[].style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  style: prismic.SelectField<"primary" | "secondary" | "tertiary">;
}

/**
 * Primary content in *HeaderNavigation → Default → Primary*
 */
export interface HeaderNavigationSliceDefaultPrimary {
  /**
   * Logo field in *HeaderNavigation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *HeaderNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.nav_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_links: prismic.GroupField<
    Simplify<HeaderNavigationSliceDefaultPrimaryNavLinksItem>
  >;

  /**
   * Action Buttons field in *HeaderNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.action_buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  action_buttons: prismic.GroupField<
    Simplify<HeaderNavigationSliceDefaultPrimaryActionButtonsItem>
  >;
}

/**
 * Default variation for HeaderNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard header with logo, links navigation (some with dropdowns), and action buttons.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderNavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderNavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderNavigation*
 */
type HeaderNavigationSliceVariation = HeaderNavigationSliceDefault;

/**
 * HeaderNavigation Shared Slice
 *
 * - **API ID**: `header_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderNavigationSlice = prismic.SharedSlice<
  "header_navigation",
  HeaderNavigationSliceVariation
>;

/**
 * Primary content in *HeadlineCtaEmail → Default → Primary*
 */
export interface HeadlineCtaEmailSliceDefaultPrimary {
  /**
   * Title field in *HeadlineCtaEmail → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_email.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeadlineCtaEmail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_email.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Input Placeholder field in *HeadlineCtaEmail → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_email.default.primary.input_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_placeholder: prismic.KeyTextField;

  /**
   * Button Text field in *HeadlineCtaEmail → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_email.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *HeadlineCtaEmail → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_email.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeadlineCtaEmail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard variation with title, description, email input, and call-to-action button.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineCtaEmailSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineCtaEmailSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadlineCtaEmail*
 */
type HeadlineCtaEmailSliceVariation = HeadlineCtaEmailSliceDefault;

/**
 * HeadlineCtaEmail Shared Slice
 *
 * - **API ID**: `headline_cta_email`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineCtaEmailSlice = prismic.SharedSlice<
  "headline_cta_email",
  HeadlineCtaEmailSliceVariation
>;

/**
 * Primary content in *HeadlineWithCtaInput → Default → Primary*
 */
export interface HeadlineWithCtaInputSliceDefaultPrimary {
  /**
   * Eyebrow field in *HeadlineWithCtaInput → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_cta_input.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *HeadlineWithCtaInput → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_cta_input.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Subheading field in *HeadlineWithCtaInput → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_cta_input.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Input Placeholder field in *HeadlineWithCtaInput → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_cta_input.default.primary.input_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_placeholder: prismic.KeyTextField;

  /**
   * CTA Button field in *HeadlineWithCtaInput → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_cta_input.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeadlineWithCtaInput Slice
 *
 * - **API ID**: `default`
 * - **Description**: Main layout with heading, supporting text, and a single input/button CTA.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineWithCtaInputSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineWithCtaInputSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadlineWithCtaInput*
 */
type HeadlineWithCtaInputSliceVariation = HeadlineWithCtaInputSliceDefault;

/**
 * HeadlineWithCtaInput Shared Slice
 *
 * - **API ID**: `headline_with_cta_input`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineWithCtaInputSlice = prismic.SharedSlice<
  "headline_with_cta_input",
  HeadlineWithCtaInputSliceVariation
>;

/**
 * Primary content in *HeadlineWithDescription → Default → Primary*
 */
export interface HeadlineWithDescriptionSliceDefaultPrimary {
  /**
   * Title field in *HeadlineWithDescription → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeadlineWithDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeadlineWithDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard two-row layout featuring a large headline and a descriptive paragraph below.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineWithDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineWithDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadlineWithDescription*
 */
type HeadlineWithDescriptionSliceVariation =
  HeadlineWithDescriptionSliceDefault;

/**
 * HeadlineWithDescription Shared Slice
 *
 * - **API ID**: `headline_with_description`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineWithDescriptionSlice = prismic.SharedSlice<
  "headline_with_description",
  HeadlineWithDescriptionSliceVariation
>;

/**
 * Primary content in *HeadlineWithSupportingText → Default → Primary*
 */
export interface HeadlineWithSupportingTextSliceDefaultPrimary {
  /**
   * Title field in *HeadlineWithSupportingText → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_supporting_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeadlineWithSupportingText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_with_supporting_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HeadlineWithSupportingText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with a title and a supporting description beneath.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineWithSupportingTextSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<HeadlineWithSupportingTextSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *HeadlineWithSupportingText*
 */
type HeadlineWithSupportingTextSliceVariation =
  HeadlineWithSupportingTextSliceDefault;

/**
 * HeadlineWithSupportingText Shared Slice
 *
 * - **API ID**: `headline_with_supporting_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineWithSupportingTextSlice = prismic.SharedSlice<
  "headline_with_supporting_text",
  HeadlineWithSupportingTextSliceVariation
>;

/**
 * Item in *HeroCta → Default → Primary → CTA Group*
 */
export interface HeroCtaSliceDefaultPrimaryCtaGroupItem {
  /**
   * Input Placeholder field in *HeroCta → Default → Primary → CTA Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta.default.primary.cta_group[].input_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_placeholder: prismic.KeyTextField;

  /**
   * Button Link field in *HeroCta → Default → Primary → CTA Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta.default.primary.cta_group[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *HeroCta → Default → Primary*
 */
export interface HeroCtaSliceDefaultPrimary {
  /**
   * Eyebrow field in *HeroCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *HeroCta → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeroCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA Group field in *HeroCta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta.default.primary.cta_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta_group: prismic.GroupField<
    Simplify<HeroCtaSliceDefaultPrimaryCtaGroupItem>
  >;
}

/**
 * Default variation for HeroCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero layout with text, description, and a single input/button call-to-action.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroCta*
 */
type HeroCtaSliceVariation = HeroCtaSliceDefault;

/**
 * HeroCta Shared Slice
 *
 * - **API ID**: `hero_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroCtaSlice = prismic.SharedSlice<
  "hero_cta",
  HeroCtaSliceVariation
>;

/**
 * Primary content in *HeroFormCta → Default → Primary*
 */
export interface HeroFormCtaSliceDefaultPrimary {
  /**
   * Title field in *HeroFormCta → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_form_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *HeroFormCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_form_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Email Input Placeholder field in *HeroFormCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_form_cta.default.primary.email_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * CTA Button field in *HeroFormCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_form_cta.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroFormCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout: heading, subheading, and a form with email input and button.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFormCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroFormCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroFormCta*
 */
type HeroFormCtaSliceVariation = HeroFormCtaSliceDefault;

/**
 * HeroFormCta Shared Slice
 *
 * - **API ID**: `hero_form_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFormCtaSlice = prismic.SharedSlice<
  "hero_form_cta",
  HeroFormCtaSliceVariation
>;

/**
 * Item in *MegaFooterNavigation → Default → Primary → Navigation Columns*
 */
export interface MegaFooterNavigationSliceDefaultPrimaryNavigationColumnsItem {
  /**
   * Column Title field in *MegaFooterNavigation → Default → Primary → Navigation Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.navigation_columns[].column_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_title: prismic.KeyTextField;

  /**
   * Links field in *MegaFooterNavigation → Default → Primary → Navigation Columns*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.navigation_columns[].links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *MegaFooterNavigation → Default → Primary → Certification Badges*
 */
export interface MegaFooterNavigationSliceDefaultPrimaryCertificationBadgesItem {
  /**
   * Badge field in *MegaFooterNavigation → Default → Primary → Certification Badges*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.certification_badges[].badge
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  badge: prismic.ImageField<never>;
}

/**
 * Item in *MegaFooterNavigation → Default → Primary → Company Addresses*
 */
export interface MegaFooterNavigationSliceDefaultPrimaryCompanyAddressesItem {
  /**
   * Address Text field in *MegaFooterNavigation → Default → Primary → Company Addresses*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.company_addresses[].address_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address_text: prismic.RichTextField;
}

/**
 * Item in *MegaFooterNavigation → Default → Primary → Social Links*
 */
export interface MegaFooterNavigationSliceDefaultPrimarySocialLinksItem {
  /**
   * Social Link field in *MegaFooterNavigation → Default → Primary → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.social_links[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Icon field in *MegaFooterNavigation → Default → Primary → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *MegaFooterNavigation → Default → Primary*
 */
export interface MegaFooterNavigationSliceDefaultPrimary {
  /**
   * Logo field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Legal Links field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.legal_links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  legal_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Navigation Columns field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.navigation_columns[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_columns: prismic.GroupField<
    Simplify<MegaFooterNavigationSliceDefaultPrimaryNavigationColumnsItem>
  >;

  /**
   * Subscribe Text field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.subscribe_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subscribe_text: prismic.RichTextField;

  /**
   * Subscribe Email Placeholder field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.subscribe_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_placeholder: prismic.KeyTextField;

  /**
   * Subscribe Action field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.subscribe_action
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subscribe_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Certification Badges field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.certification_badges[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  certification_badges: prismic.GroupField<
    Simplify<MegaFooterNavigationSliceDefaultPrimaryCertificationBadgesItem>
  >;

  /**
   * Copyright field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.copyright
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField;

  /**
   * Company Addresses field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.company_addresses[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  company_addresses: prismic.GroupField<
    Simplify<MegaFooterNavigationSliceDefaultPrimaryCompanyAddressesItem>
  >;

  /**
   * Social Links field in *MegaFooterNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_footer_navigation.default.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<MegaFooterNavigationSliceDefaultPrimarySocialLinksItem>
  >;
}

/**
 * Default variation for MegaFooterNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard multi-column structured footer with navigation, subscription, and legal/branding elements.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MegaFooterNavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MegaFooterNavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MegaFooterNavigation*
 */
type MegaFooterNavigationSliceVariation = MegaFooterNavigationSliceDefault;

/**
 * MegaFooterNavigation Shared Slice
 *
 * - **API ID**: `mega_footer_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MegaFooterNavigationSlice = prismic.SharedSlice<
  "mega_footer_navigation",
  MegaFooterNavigationSliceVariation
>;

/**
 * Item in *NavigationBar → Default → Primary → Menu Items*
 */
export interface NavigationBarSliceDefaultPrimaryMenuItemsItem {
  /**
   * Menu Label field in *NavigationBar → Default → Primary → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Has Dropdown field in *NavigationBar → Default → Primary → Menu Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.menu_items[].has_dropdown
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_dropdown: prismic.BooleanField;

  /**
   * Menu Link field in *NavigationBar → Default → Primary → Menu Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.menu_items[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Dropdown Id field in *NavigationBar → Default → Primary → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.menu_items[].dropdown_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dropdown_id: prismic.KeyTextField;
}

/**
 * Item in *NavigationBar → Default → Primary → Action Buttons*
 */
export interface NavigationBarSliceDefaultPrimaryActionButtonsItem {
  /**
   * Button Label field in *NavigationBar → Default → Primary → Action Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.action_buttons[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Button Link field in *NavigationBar → Default → Primary → Action Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.action_buttons[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Button Style field in *NavigationBar → Default → Primary → Action Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.action_buttons[].style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  style: prismic.SelectField<"primary" | "secondary">;
}

/**
 * Primary content in *NavigationBar → Default → Primary*
 */
export interface NavigationBarSliceDefaultPrimary {
  /**
   * Logo field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menu Items field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.menu_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_items: prismic.GroupField<
    Simplify<NavigationBarSliceDefaultPrimaryMenuItemsItem>
  >;

  /**
   * Action Buttons field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.action_buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  action_buttons: prismic.GroupField<
    Simplify<NavigationBarSliceDefaultPrimaryActionButtonsItem>
  >;
}

/**
 * Default variation for NavigationBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: The standard navigation bar with logo, menu links (some with dropdowns), and a pair of call-to-action buttons aligned right.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationBar*
 */
type NavigationBarSliceVariation = NavigationBarSliceDefault;

/**
 * NavigationBar Shared Slice
 *
 * - **API ID**: `navigation_bar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationBarSlice = prismic.SharedSlice<
  "navigation_bar",
  NavigationBarSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      FeatureHighlightSplitSlice,
      FeatureHighlightSplitSliceDefaultWithThreeFeaturesPrimarySlidesItem,
      FeatureHighlightSplitSliceDefaultWithThreeFeaturesPrimary,
      FeatureHighlightSplitSliceVariation,
      FeatureHighlightSplitSliceDefaultWithThreeFeatures,
      FeatureHighlightSplit2Slice,
      FeatureHighlightSplit2SliceDefaultPrimaryFeaturesItem,
      FeatureHighlightSplit2SliceDefaultPrimary,
      FeatureHighlightSplit2SliceVariation,
      FeatureHighlightSplit2SliceDefault,
      FeatureWithVisualAndTextSlice,
      FeatureWithVisualAndTextSliceVisualLeftTextRightPrimary,
      FeatureWithVisualAndTextSliceVariation,
      FeatureWithVisualAndTextSliceVisualLeftTextRight,
      FooterNavigationSlice,
      FooterNavigationSliceDefaultLayoutPrimaryNavigationColumnsItem,
      FooterNavigationSliceDefaultLayoutPrimaryCertificationBadgesItem,
      FooterNavigationSliceDefaultLayoutPrimaryLegalLinksItem,
      FooterNavigationSliceDefaultLayoutPrimarySocialLinksItem,
      FooterNavigationSliceDefaultLayoutPrimary,
      FooterNavigationSliceVariation,
      FooterNavigationSliceDefaultLayout,
      HeaderNavigationSlice,
      HeaderNavigationSliceDefaultPrimaryNavLinksItem,
      HeaderNavigationSliceDefaultPrimaryActionButtonsItem,
      HeaderNavigationSliceDefaultPrimary,
      HeaderNavigationSliceVariation,
      HeaderNavigationSliceDefault,
      HeadlineCtaEmailSlice,
      HeadlineCtaEmailSliceDefaultPrimary,
      HeadlineCtaEmailSliceVariation,
      HeadlineCtaEmailSliceDefault,
      HeadlineWithCtaInputSlice,
      HeadlineWithCtaInputSliceDefaultPrimary,
      HeadlineWithCtaInputSliceVariation,
      HeadlineWithCtaInputSliceDefault,
      HeadlineWithDescriptionSlice,
      HeadlineWithDescriptionSliceDefaultPrimary,
      HeadlineWithDescriptionSliceVariation,
      HeadlineWithDescriptionSliceDefault,
      HeadlineWithSupportingTextSlice,
      HeadlineWithSupportingTextSliceDefaultPrimary,
      HeadlineWithSupportingTextSliceVariation,
      HeadlineWithSupportingTextSliceDefault,
      HeroCtaSlice,
      HeroCtaSliceDefaultPrimaryCtaGroupItem,
      HeroCtaSliceDefaultPrimary,
      HeroCtaSliceVariation,
      HeroCtaSliceDefault,
      HeroFormCtaSlice,
      HeroFormCtaSliceDefaultPrimary,
      HeroFormCtaSliceVariation,
      HeroFormCtaSliceDefault,
      MegaFooterNavigationSlice,
      MegaFooterNavigationSliceDefaultPrimaryNavigationColumnsItem,
      MegaFooterNavigationSliceDefaultPrimaryCertificationBadgesItem,
      MegaFooterNavigationSliceDefaultPrimaryCompanyAddressesItem,
      MegaFooterNavigationSliceDefaultPrimarySocialLinksItem,
      MegaFooterNavigationSliceDefaultPrimary,
      MegaFooterNavigationSliceVariation,
      MegaFooterNavigationSliceDefault,
      NavigationBarSlice,
      NavigationBarSliceDefaultPrimaryMenuItemsItem,
      NavigationBarSliceDefaultPrimaryActionButtonsItem,
      NavigationBarSliceDefaultPrimary,
      NavigationBarSliceVariation,
      NavigationBarSliceDefault,
    };
  }
}
