// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  feature_highlight_split: dynamic(() => import("./FeatureHighlightSplit")),
  feature_highlight_with_illustration: dynamic(
    () => import("./FeatureHighlightWithIllustration"),
  ),
  feature_with_visual_and_text: dynamic(
    () => import("./FeatureWithVisualAndText"),
  ),
  footer_navigation: dynamic(() => import("./FooterNavigation")),
  header_navigation: dynamic(() => import("./HeaderNavigation")),
  headline_cta_email: dynamic(() => import("./HeadlineCtaEmail")),
  headline_with_cta_input: dynamic(() => import("./HeadlineWithCtaInput")),
  headline_with_description: dynamic(() => import("./HeadlineWithDescription")),
  headline_with_supporting_text: dynamic(
    () => import("./HeadlineWithSupportingText"),
  ),
  hero_cta: dynamic(() => import("./HeroCta")),
  hero_form_cta: dynamic(() => import("./HeroFormCta")),
  mega_footer_navigation: dynamic(() => import("./MegaFooterNavigation")),
  navigation_bar: dynamic(() => import("./NavigationBar")),
  visual_text_combo: dynamic(() => import("./VisualTextCombo")),
};
